name: "Stability Test"

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          coverage: xdebug

      - name: Check PHP Version
        run: php -v

      - name: Validate Composer
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Package Audit
        run: composer audit
